services:
  - type: web
    name: rasa-server
    plan: free
    dockerfilePath: Dockerfile
    startCommand: rasa run --enable-api --cors "*" --port 5005
    runtime: python

  - type: web
    name: rasa-actions
    plan: free
    dockerfilePath: Dockerfile
    startCommand: rasa run actions --port 5055
    runtime: python